# -----------------------------------------------------------------------------
# File:        Makefile
# Path:        bootloader/cores/misc/Makefile
#
# Project:     Hazard3-Doom
# Purpose:     Build and test the vendored miscellaneous utility core.
#
# Original author(s):    Sylvain Munaut (smunaut)
#
# Upstream:    HAD2019 misc utility core
# Upstream license: No file-level license notice was present in this
#                   imported upstream file; do not infer one here.
#
# This file contains third-party material and is not relicensed by
# Hazard3-Doom. Preserve its upstream history and provenance.
# See LICENSES/HAD2019-Bootloader-NOTICE.md for provenance and licensing.
# See LICENSING.md for project licensing policy and scope.
# -----------------------------------------------------------------------------

CORE := misc

include ../../mk/core-rules.mk
