name: tt-fpga-ulx

# This is a modified fpga workflow that adds ULX3S ECP5 support
#
# See upstream:
#   https://github.com/TinyTapeout/ttsky-verilog-template/issues/22
#   https://github.com/TinyTapeout/tt-support-tools/pull/167
#   https://github.com/TinyTapeout/tt-gds-action/pull/47
#   https://github.com/TinyTapeout/ttsky-verilog-template/pull/23
#   https://github.com/TinyTapeout/ttsky-verilog-template/pull/25

on:
  push:
    # Comment out (or remove) the following line to run the FPGA workflow on every push:
    # branches: none
  workflow_dispatch:

permissions:
  # explicit least-privilege setting for GITHUB_TOKEN, no write permissions needed
  contents: read

jobs:
  fpga-ice40:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: FPGA bitstream for TT ASIC Sim (iCE40 UP5K)
        uses: ulx3s/tt-gds-action/fpga/ice40up5k@experimental


  fpga-ulx3s:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: FPGA bitstream for TT ASIC Sim (ULX3S ECP5)
        uses: ulx3s/tt-gds-action/fpga/ulx3s@experimental
        with:
          ecp5-device: 85k
          lpf: tt/fpga/ulx3s/ulx3s_v20.lpf
          artifact-name: fpga_ulx3s_ecp5
          uart-enabled: true
